/**
 * This file is autogenerated from a template. Please do not edit it directly.
 * Please edit ./take-while.template.js
 * then rebuild with:
 * > npm run build
 * More information can be found in CONTRIBUTING.md
 */

import { curry } from "./internal/iterable";

function* takeWhile(func, i) {
  let take = true;
  let c = 0;

  for (const item of i) {
    take = func(item, c++);

    if (take) {
      yield item;
    } else {
      break;
    }
  }
}

export default curry(takeWhile);